name: Test generated artifacts

on: [pull_request]

jobs:
  build:
    name: Registry Hunter Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: '^1.20'
      id: go

    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        submodules: recursive

    - name: Download Latest Velociraptor
      uses: robinraju/release-downloader@v1
      id: velociraptor
      with:
        repository: velocidex/velociraptor
        tag: v0.75
        fileName: "velociraptor-v0.75.2-linux-amd64-musl"
        out-file-path: tests

    - name: Build artifacts
      run: |
        make all recmd artifact

    - name: Run Velociraptor
      run: |
        mv ${{ fromJson(steps.velociraptor.outputs.downloaded_files)[0]}} ./tests/velociraptor
        chmod +x ./tests/velociraptor
        ls -l ./output/
        ./tests/velociraptor artifacts verify --builtin -v ./output/*.yaml

    - name: Run tests
      run: |
        make test

    - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
      if: always()
      with:
        name: output
        path: output
